tokenizer:
  model_name: gpt2
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: True

reward_fn:
  id: "intent_accuracy"
  args:
    intent_coeff: 0.75
    auto_coeff: 0.25


datapool:
  id: "daily_dialog"
  args:
    context_size: 5

env:
  args:
    max_prompt_length: 128
    max_episode_length: 20
    terminate_on_eos: True

alg:
  id: bail
  args:
    gamma: 0.99
    buffer_size: 128000
    seed: 0
    norm_reward: False
    
  kl_div:
    coeff: 0.2
    target_kl: 0.5
 
  policy:
    id: causal_lm_actor_critic_policy
    args:
      model_name: gpt2
      apply_model_parallel: True
      generation_kwargs:
        do_sample: True
        top_k: 20
        min_length: 2
        max_new_tokens: 20
      
train_evaluation:
  bail_learn:
    seed: 0
    ue_lr: 0.00001
    ue_wd: 0.02
    ue_loss_k: 1000
    ue_train_epoch: 10
    ue_batch_size: 16
    ue_consecutive_steps: 3
#    ue_clip: None
    pct: 0.35

  n_epochs: 30
  train_batch_size: 8
  n_batch: 100
  learning_rate: 0.000001
  weight_decay: 0
  beta: 0.05

  eval_batch_size: 8
  eval_every: 3
  save_every: 10
  metrics:
    - id: intent_accuracy
#    - id: causal_perplexity
#      args:
#        tokenizer_id: gpt2
#        stride: 128
#        model_type: causal
#    - id: diversity
#      args: {}
#    - id: meteor
#      args: {}
#    - id: rouge
#    - id: bleu
#      args: {}
    - id: bert_score
      args:
        language: en
#    - id: sacre_bleu
#      args:
#        tokenize: "intl"
  generation_kwargs:
    do_sample: True
    top_k: 20
    min_length: 2
    max_new_tokens: 20
